std namespace error
forgot to use std namespace
In file included from src/sec_connection.cpp:22:0:
src/client.hpp:22:44: error: expected class-name before â{â token
struct connection_error: public exception {